language: objective-c
osx_image: xcode14.3.1
xcode_workspace: demoCICD.xcworkspace
xcode_scheme: demoCICD_dev
xcode_destination: platform=iOS Simulator,OS=17.2,name=iPhone 14 Pro
before_install:
  - bundle install
  - bundle exec pod install --repo-update
